export const CONSTANTS = {
  GET_ALL_GENERS: "GET_ALL_GENERS",
  GET_ALL_VIDEOGAMES: "GET_ALL_VIDEOGAMES",
  GET_ID_VIDEOGAME: "GET_ID_VIDEOGAME",
  GET_ALL_FAVORITES: "GET_ALL_FAVORITES",
  GET_ALL_PURCHASED: "GET_ALL_PURCHASED",

  SET_USER_AUTH0: "SET_USER_AUTH0",

  LOGIN: "LOGIN",
  FILTERS: "FILTERS",

  CLEAN_VIDEOGAMES: "CLEAN_VIDEOGAMES",

  SET_MESSAGE: "SET_MESSAGE",

  ADD_REDUX_FAVORITE: "ADD_REDUX_FAVORITE",
  DELETE_REDUX_FAVORITE: "DELETE_REDUX_FAVORITE"

}

