export const CONSTANTS = {
  GET_ALL_GENERS: "GET_ALL_GENERS",
  GET_ALL_VIDEOGAMES: "GET_ALL_VIDEOGAMES",
  GET_ID_VIDEOGAME: "GET_ID_VIDEOGAME",
  
  LOGIN: "LOGIN",
  FILTERS: "FILTERS",

  CLEAN_VIDEOGAMES: "CLEAN_VIDEOGAMES",

  SET_MESSAGE: "SET_MESSAGE"

}

